Update configs. Update workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,18 +12,32 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Create Image Tarball for explorer-frontend
-        run: |
-          git clone https://github.com/Atleta-network/blockscout-frontend.git
-          cd blockscout-frontend
-          git checkout develop
-          docker build \
-            --build-arg GIT_COMMIT_SHA=$(git rev-parse --short HEAD) \
-            --build-arg GIT_TAG=$(git describe --tags --abbrev=0) \
-            --tag explorer-frontend ./
-          cd ../
-          mkdir -p artifacts
-          docker save explorer-frontend > artifacts/explorer-frontend.tar
+      - name: Checkout blockscout-frontend repository
+        uses: actions/checkout@v4
+        with:
+          repository: Atleta-network/blockscout-frontend
+          ref: develop
+          path: blockscout-frontend
+
+      - name: Log in to Docker Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ secrets.CI_REGISTRY }}
+          username: ${{ secrets.CI_REGISTRY_USER }}
+          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
+
+      - name: Build and push explorer-frontend image
+        uses: docker/build-push-action@v5
+        with:
+          context: ./blockscout-frontend
+          push: true
+          no-cache: true
+          tags: |
+            ${{ secrets.CI_REGISTRY }}/${{ secrets.CI_REGISTRY_REPO }}/blockscout-frontend:${{ github.sha }}
+            ${{ secrets.CI_REGISTRY }}/${{ secrets.CI_REGISTRY_REPO }}/blockscout-frontend:latest
+          build-args: |
+            GIT_COMMIT_SHA=${{ github.sha }}
+            GIT_TAG=develop
 
       - name: Install system dependencies
         run: |
@@ -33,12 +47,12 @@ jobs:
         run: |
           mkdir -p ~/.ssh/
           touch ~/.ssh/known_hosts
-          ssh-keyscan ${{ secrets.EXPLORER_HOST }} >> ~/.ssh/known_hosts
+          ssh-keyscan ${{ secrets.HOST_1 }} >> ~/.ssh/known_hosts
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           eval $(ssh-agent)
 
-      - name: Fill .env file
+      - name: Fill common-frontend.env
         env:
           NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
         run: |
@@ -52,21 +66,56 @@ jobs:
             mkdir .well-known
             echo ${{ secrets.WALLETCONNECT}} > ./.well-known/walletconnect.txt
 
+      - name: Fill common-frontend.env
+        env:
+          CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
+          CI_REGISTRY_REPO: ${{ secrets.CI_REGISTRY_REPO }}
+          SERVICE_NAME: blockscout-frontend
+          SERVICE_TAG: ${{ github.sha }}
+        run: |
+            cd docker-compose/services
+            envsubst < frontend.yml > frontend_fill.yml
+            mv frontend_fill.yml frontend.yml
+
       - name: Copy Files to Server
         run: |
-          scp -r docker-compose/*    ${{ secrets.HOST_USER}}@${{ secrets.EXPLORER_HOST }}:/blockscout
-          scp -r artifacts/*    ${{ secrets.HOST_USER}}@${{ secrets.EXPLORER_HOST }}:/blockscout
+          scp -r docker-compose/* ${{ secrets.HOST_1_USERNAME}}@${{ secrets.HOST_1 }}:${{ secrets.BASE_PATH }}
 
-      - name: SSH into Server and Deploy
+      - name: Deploy
         uses: appleboy/ssh-action@v1.0.0
+        env:
+          CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
+          CI_REGISTRY_REPO: ${{ secrets.CI_REGISTRY_REPO }}
+          SERVICE_NAME: blockscout-frontend
+          SERVICE_TAG: ${{ github.sha }}
+          DOCKER_COMPOSE_FILE: ${{ vars.DOCKER_COMPOSE_FILE }}
+          BASE_PATH: ${{ secrets.BASE_PATH }}
         with:
-          host: ${{ secrets.EXPLORER_HOST }}
-          username: ${{ secrets.HOST_USER }}
+          host: ${{ secrets.HOST_1 }}
+          username: ${{ secrets.HOST_1_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
+          envs: CI_REGISTRY,CI_REGISTRY_REPO,SERVICE_NAME,SERVICE_TAG,DOCKER_COMPOSE_FILE,BASE_PATH
           script: |
-            cd /blockscout
-            docker load --input explorer-frontend.tar
-            docker rm -f backend || true
+            for var in CI_REGISTRY CI_REGISTRY_REPO SERVICE_NAME SERVICE_TAG DOCKER_COMPOSE_FILE,BASE_PATH; do
+              if [ -z "${!var}" ]; then
+                echo "Error: Environment variable ${var} is not set."
+                exit 1
+              fi
+            done
+
+            IMAGE="${CI_REGISTRY}/${CI_REGISTRY_REPO}/${SERVICE_NAME}:${SERVICE_TAG}"
+
+            update_docker_compose() {
+              local image="$1"
+              local compose_file="$2"
+              sed -i "s|image: .*/${SERVICE_NAME}:.*|image: ${image}|" "${compose_file}"
+            }
+          
+            cd "${BASE_PATH}/services" || exit 1
+          
+            update_docker_compose "${IMAGE}" "${DOCKER_COMPOSE_FILE}"
+
+            cd "${BASE_PATH}" || exit 1
+
             docker compose down || true
-            docker compose pull || true
             docker compose up --detach
